service: omni-quotes-info-poc

provider:
  name: aws
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  versionFunctions: false
  tags: ${self:custom.tags}
  stackTags: ${self:custom.tags}
  iam:
    role:
      name: ${self:service}-${self:provider.stage}-role
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
            - s3:ListBucket
          Resource: 
            - "arn:aws:s3:::omni-quotes-info-poc"
            - "arn:aws:s3:::omni-quotes-info-poc/*"
  vpc:
    securityGroupIds:
      - ${ssm:/omni-dw/${self:provider.stage}/lambda/sgId}
    subnetIds:
      - ${ssm:/omni-dw/${self:provider.stage}/lambda/subnetA}
  runtime: nodejs14.x
  deploymentBucket: 
    name: ${ssm:/omni-dw/${self:provider.stage}/sls/deployment/bucket}
    serverSideEncryption: AES256

custom:
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  tags:
    Application: omni-quotes-info-poc
    CreatedBy: Bizcloudexperts
    Environment: ${self:custom.stage}

plugins:
 - serverless-offline

package:
  individually: true

layers:
  OmniQuotesInfoPocLayer:
    path: lambdaLayer/lib
    name: ${self:service}-layer-${self:provider.stage}
    description: Omni quotes info poc lambda layer for all node modules - ${self:provider.stage}
    compatibleRuntimes:
      - nodejs14.x
    retain: false

functions:
  omniQuotesInfo: ${file(config/functions/omniQuotesInfo.yml):function}